// Last Minute — Tool Directory Data
// 65+ free/low-cost tools for students, hackathons, research, and rapid prototyping

export type ToolCategory =
    | 'ppt-slides'
    | 'video-animation'
    | 'app-building'
    | 'deployment'
    | 'research-ai'
    | 'code-debug'
    | 'design'
    | 'writing-docs'
    | 'music-audio'
    | 'utilities'

export interface Tool {
    id: string
    name: string
    url: string
    description: string
    category: ToolCategory
    pricing: 'Free' | 'Freemium' | 'Free Trial' | 'Low-Cost'
    tags: string[]
    icon: string // emoji
    hackathonPrompt?: string // AI-generated prompt for hackathon use
    noSignup?: boolean
}

export interface Workflow {
    id: string
    title: string
    description: string
    icon: string
    tools: string[] // tool ids
    steps: string[]
    useCase: string
}

export const CATEGORY_META: Record<ToolCategory, { label: string; icon: string; color: string }> = {
    'ppt-slides': { label: 'PPT / Slides', icon: '📊', color: '#f59e0b' },
    'video-animation': { label: 'Video / Animation', icon: '🎬', color: '#ef4444' },
    'app-building': { label: 'App Building', icon: '🛠️', color: '#8b5cf6' },
    'deployment': { label: 'Deploy / Hosting', icon: '🚀', color: '#06b6d4' },
    'research-ai': { label: 'Research & AI', icon: '🔬', color: '#10b981' },
    'code-debug': { label: 'Code / Debug', icon: '💻', color: '#3b82f6' },
    'design': { label: 'Design / UI', icon: '🎨', color: '#ec4899' },
    'writing-docs': { label: 'Writing / Docs', icon: '✍️', color: '#f97316' },
    'music-audio': { label: 'Music / Audio', icon: '🎵', color: '#a855f7' },
    'utilities': { label: 'Utilities', icon: '🧰', color: '#64748b' },
}

export const TOOLS: Tool[] = [
    // ─── PPT / SLIDES ─────────────────────────────────────────────
    {
        id: 'gamma',
        name: 'Gamma.app',
        url: 'https://gamma.app/signup?r=irt8vkl7gwvm2wd',
        description: 'AI-powered presentation generator. Paste your topic and get a polished PPT in seconds.',
        category: 'ppt-slides',
        pricing: 'Freemium',
        tags: ['ai', 'ppt', 'slides', 'hackathon', 'presentation'],
        icon: '⚡',
        hackathonPrompt: `Create a 10-slide hackathon demo deck for [PROJECT_NAME]. Include: Problem Statement, Solution Overview, Tech Stack, Architecture Diagram placeholder, Key Features (3), Demo Screenshots placeholders, Business Model, Market Size, Team Slide, and Call to Action. Use modern dark theme with gradient accents.`,
    },
    {
        id: 'canva-slides',
        name: 'Canva Slides',
        url: 'https://www.canva.com/presentations/',
        description: 'Drag-and-drop slide maker with 1000s of free templates. Great for non-designers.',
        category: 'ppt-slides',
        pricing: 'Freemium',
        tags: ['design', 'templates', 'ppt', 'free'],
        icon: '🎨',
        hackathonPrompt: `Search "hackathon pitch deck" in templates. Pick a dark modern template. Replace placeholder text with: Slide 1 - Project name & tagline, Slide 2 - Problem, Slide 3 - Solution, Slide 4 - Demo, Slide 5 - Tech Stack, Slide 6 - Team, Slide 7 - Next Steps.`,
    },
    {
        id: 'slidesai',
        name: 'SlidesAI.io',
        url: 'https://www.slidesai.io',
        description: 'Google Slides AI add-on — paste text and auto-generate professional slides.',
        category: 'ppt-slides',
        pricing: 'Freemium',
        tags: ['google-slides', 'ai', 'addon'],
        icon: '📑',
    },
    {
        id: 'beautiful-ai',
        name: 'Beautiful.ai',
        url: 'https://www.beautiful.ai',
        description: 'Smart slide design with auto-layout. Templates adapt to your content.',
        category: 'ppt-slides',
        pricing: 'Free Trial',
        tags: ['design', 'smart-layout', 'professional'],
        icon: '✨',
    },
    {
        id: 'tome',
        name: 'Tome',
        url: 'https://tome.app',
        description: 'AI storytelling tool that creates narrative presentations from prompts.',
        category: 'ppt-slides',
        pricing: 'Freemium',
        tags: ['ai', 'narrative', 'storytelling'],
        icon: '📖',
    },
    {
        id: 'pitch',
        name: 'Pitch',
        url: 'https://pitch.com',
        description: 'Collaborative presentation software with beautiful templates and real-time editing.',
        category: 'ppt-slides',
        pricing: 'Freemium',
        tags: ['collaboration', 'templates', 'team'],
        icon: '🎯',
    },

    // ─── VIDEO / ANIMATION ────────────────────────────────────────
    {
        id: 'capcut',
        name: 'CapCut',
        url: 'https://www.capcut.com',
        description: 'Free professional video editor with effects, transitions, and AI captions.',
        category: 'video-animation',
        pricing: 'Free',
        tags: ['video', 'editing', 'free', 'effects'],
        icon: '🎬',
        hackathonPrompt: `Import your screen recording. Add: Intro title (3s) with project name, background music (lo-fi), captions via Auto Caption, smooth transitions between clips, and an outro with team name. Export at 1080p.`,
    },
    {
        id: 'runwayml',
        name: 'RunwayML',
        url: 'https://runwayml.com',
        description: 'AI video generation and editing — text-to-video, green screen, motion tracking.',
        category: 'video-animation',
        pricing: 'Freemium',
        tags: ['ai', 'video-gen', 'effects', 'ml'],
        icon: '🤖',
    },
    {
        id: 'veed',
        name: 'VEED.io',
        url: 'https://www.veed.io',
        description: 'Online video editor with subtitles, screen recording, and social media export.',
        category: 'video-animation',
        pricing: 'Freemium',
        tags: ['subtitles', 'screen-record', 'social'],
        icon: '📹',
    },
    {
        id: 'invideo',
        name: 'InVideo AI',
        url: 'https://invideo.io',
        description: 'AI video creator — describe your video and it generates one with stock footage.',
        category: 'video-animation',
        pricing: 'Freemium',
        tags: ['ai', 'auto-generate', 'stock-footage'],
        icon: '🎥',
        hackathonPrompt: `Use AI Script: "Create a 60-second product demo video for [PROJECT_NAME]. It's a [DESCRIPTION]. Show the problem, the solution, and a call to action. Use professional tech startup style."`,
    },
    {
        id: 'loom',
        name: 'Loom',
        url: 'https://www.loom.com',
        description: 'Quick screen & cam recording for demos. Share instantly with a link.',
        category: 'video-animation',
        pricing: 'Freemium',
        tags: ['screen-record', 'demo', 'quick'],
        icon: '🔴',
        hackathonPrompt: `Record a 3-minute demo: 1) Intro yourself & project (30s), 2) Show the problem you're solving (30s), 3) Live demo of your app (90s), 4) Wrap up with future plans (30s). Share the Loom link in your pitch deck.`,
    },
    {
        id: 'descript',
        name: 'Descript',
        url: 'https://www.descript.com',
        description: 'Edit video by editing text. AI-powered transcription and screen recording.',
        category: 'video-animation',
        pricing: 'Freemium',
        tags: ['transcription', 'text-edit', 'ai'],
        icon: '📝',
    },
    {
        id: 'clipchamp',
        name: 'Clipchamp',
        url: 'https://clipchamp.com',
        description: 'Microsoft free video editor with templates, stock media, and text-to-speech.',
        category: 'video-animation',
        pricing: 'Free',
        tags: ['microsoft', 'free', 'templates'],
        icon: '🎞️',
    },

    // ─── APP BUILDING ─────────────────────────────────────────────
    {
        id: 'bubble',
        name: 'Bubble.io',
        url: 'https://bubble.io',
        description: 'Full-stack no-code app builder. Build web apps with visual workflows, DB, and auth.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['no-code', 'full-stack', 'webapp'],
        icon: '🫧',
    },
    {
        id: 'adalo',
        name: 'Adalo',
        url: 'https://www.adalo.com',
        description: 'Build native mobile apps without code. Drag-and-drop with real app store publishing.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['mobile', 'no-code', 'native'],
        icon: '📱',
    },
    {
        id: 'glide',
        name: 'Glide',
        url: 'https://www.glideapps.com',
        description: 'Turn Google Sheets into beautiful apps in minutes. Perfect for MVPs.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['sheets', 'mvp', 'quick'],
        icon: '📋',
    },
    {
        id: 'replit',
        name: 'Replit Agent',
        url: 'https://replit.com',
        description: 'AI code-to-app — describe what you want and Replit builds it. Full IDE in browser.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['ai', 'code', 'ide', 'deploy'],
        icon: '⚙️',
        hackathonPrompt: `Use Replit Agent: "Build a [TYPE] web app with [FRAMEWORK]. It should have: user auth, a dashboard showing [DATA], and an API endpoint at /api/[RESOURCE]. Use a modern dark UI with Tailwind CSS. Deploy to Replit hosting."`,
    },
    {
        id: 'v0-dev',
        name: 'v0.dev',
        url: 'https://v0.dev',
        description: 'Vercel AI UI generator — describe a component and get production React code.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['ai', 'react', 'ui-gen', 'vercel'],
        icon: '▲',
    },
    {
        id: 'bolt',
        name: 'bolt.new',
        url: 'https://bolt.new',
        description: 'AI full-stack app builder by StackBlitz. Describe your app and get a running project.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['ai', 'full-stack', 'instant'],
        icon: '⚡',
    },
    {
        id: 'lovable',
        name: 'Lovable.dev',
        url: 'https://lovable.dev',
        description: 'AI app builder — create full-stack apps from natural language descriptions.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['ai', 'full-stack', 'natural-language'],
        icon: '💜',
    },
    {
        id: 'flutterflow',
        name: 'FlutterFlow',
        url: 'https://flutterflow.io',
        description: 'Visual Flutter app builder. Design, build, and deploy mobile apps with Firebase.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['flutter', 'mobile', 'visual', 'firebase'],
        icon: '🦋',
    },

    // ─── DEPLOYMENT / HOSTING ─────────────────────────────────────
    {
        id: 'vercel',
        name: 'Vercel',
        url: 'https://vercel.com',
        description: 'Instant deploy for Next.js, React, and more. Free tier with custom domains.',
        category: 'deployment',
        pricing: 'Freemium',
        tags: ['nextjs', 'react', 'deploy', 'free'],
        icon: '▲',
    },
    {
        id: 'netlify',
        name: 'Netlify Drop',
        url: 'https://app.netlify.com/drop',
        description: 'Drag-and-drop deploy. Literally drag your folder and get a live URL.',
        category: 'deployment',
        pricing: 'Free',
        tags: ['drag-drop', 'instant', 'static'],
        icon: '🌐',
        noSignup: true,
    },
    {
        id: 'render',
        name: 'Render.com',
        url: 'https://render.com',
        description: 'Deploy web services, static sites, databases, and cron jobs. Generous free tier.',
        category: 'deployment',
        pricing: 'Freemium',
        tags: ['backend', 'database', 'fullstack'],
        icon: '🟢',
    },
    {
        id: 'railway',
        name: 'Railway.app',
        url: 'https://railway.app',
        description: 'Deploy any app with one click. Supports Node, Python, Go, Docker, and more.',
        category: 'deployment',
        pricing: 'Freemium',
        tags: ['one-click', 'docker', 'backend'],
        icon: '🚂',
    },
    {
        id: 'github-pages',
        name: 'GitHub Pages',
        url: 'https://pages.github.com',
        description: 'Free static site hosting from your GitHub repo. Perfect for portfolios and docs.',
        category: 'deployment',
        pricing: 'Free',
        tags: ['github', 'static', 'free'],
        icon: '🐙',
    },
    {
        id: 'surge',
        name: 'Surge.sh',
        url: 'https://surge.sh',
        description: 'Single command deploy for static sites. No config needed.',
        category: 'deployment',
        pricing: 'Free',
        tags: ['cli', 'static', 'instant'],
        icon: '🌊',
        noSignup: true,
    },
    {
        id: 'supabase',
        name: 'Supabase',
        url: 'https://supabase.com',
        description: 'Open-source Firebase alternative with Postgres, Auth, Storage, and Edge Functions.',
        category: 'deployment',
        pricing: 'Freemium',
        tags: ['database', 'auth', 'storage', 'backend'],
        icon: '⚡',
    },

    // ─── RESEARCH & AI ────────────────────────────────────────────
    {
        id: 'perplexity',
        name: 'Perplexity.ai',
        url: 'https://www.perplexity.ai',
        description: 'AI research assistant with real-time sources. Ask anything, get cited answers.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['research', 'ai', 'citations', 'search'],
        icon: '🔍',
        hackathonPrompt: `Search: "Latest trends in [YOUR_DOMAIN] 2026 with statistics". Use the cited sources in your pitch deck. Then search: "Existing solutions for [PROBLEM] and their limitations" for competitive analysis.`,
    },
    {
        id: 'consensus',
        name: 'Consensus.app',
        url: 'https://consensus.app',
        description: 'AI-powered academic paper search. Find research evidence for any claim.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['papers', 'academic', 'evidence'],
        icon: '📚',
    },
    {
        id: 'elicit',
        name: 'Elicit.org',
        url: 'https://elicit.org',
        description: 'AI literature review tool. Finds and summarizes relevant papers for your research.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['literature-review', 'papers', 'summary'],
        icon: '🔬',
    },
    {
        id: 'scite',
        name: 'Scite.ai',
        url: 'https://scite.ai',
        description: 'See how papers cite each other — supporting, contrasting, or mentioning.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['citations', 'analysis', 'papers'],
        icon: '📖',
    },
    {
        id: 'chatgpt',
        name: 'ChatGPT',
        url: 'https://chat.openai.com',
        description: 'OpenAI conversational AI. Code, brainstorm, write, debug, and research.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['ai', 'chat', 'code', 'writing'],
        icon: '🤖',
    },
    {
        id: 'claude',
        name: 'Claude.ai',
        url: 'https://claude.ai',
        description: 'Anthropic AI assistant. Excels at long documents, coding, and analysis.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['ai', 'analysis', 'code', 'documents'],
        icon: '🧠',
    },
    {
        id: 'gemini',
        name: 'Google Gemini',
        url: 'https://gemini.google.com',
        description: 'Google AI with web search, image generation, and deep research mode.',
        category: 'research-ai',
        pricing: 'Free',
        tags: ['ai', 'google', 'search', 'multimodal'],
        icon: '💎',
    },
    {
        id: 'notebook-lm',
        name: 'NotebookLM',
        url: 'https://notebooklm.google.com',
        description: 'Google AI notebook — upload papers/docs and chat with them. Auto-generates podcasts.',
        category: 'research-ai',
        pricing: 'Free',
        tags: ['google', 'documents', 'podcast', 'study'],
        icon: '📓',
    },
    {
        id: 'semantic-scholar',
        name: 'Semantic Scholar',
        url: 'https://www.semanticscholar.org',
        description: 'AI-powered academic search engine with paper recommendations and citations.',
        category: 'research-ai',
        pricing: 'Free',
        tags: ['academic', 'papers', 'free', 'search'],
        icon: '🎓',
    },

    // ─── CODE / DEBUG ─────────────────────────────────────────────
    {
        id: 'codepen',
        name: 'CodePen',
        url: 'https://codepen.io',
        description: 'Online code playground for HTML/CSS/JS. Instant preview and sharing.',
        category: 'code-debug',
        pricing: 'Freemium',
        tags: ['playground', 'html', 'css', 'js'],
        icon: '✏️',
        noSignup: true,
    },
    {
        id: 'jsfiddle',
        name: 'JSFiddle',
        url: 'https://jsfiddle.net',
        description: 'Quick JS/HTML/CSS prototypes. Share snippets with collaborators.',
        category: 'code-debug',
        pricing: 'Free',
        tags: ['playground', 'prototype', 'share'],
        icon: '🎻',
        noSignup: true,
    },
    {
        id: 'codesandbox',
        name: 'CodeSandbox',
        url: 'https://codesandbox.io',
        description: 'Full online IDE with npm, frameworks, and instant deployment.',
        category: 'code-debug',
        pricing: 'Freemium',
        tags: ['ide', 'npm', 'react', 'vue'],
        icon: '📦',
    },
    {
        id: 'stackblitz',
        name: 'StackBlitz',
        url: 'https://stackblitz.com',
        description: 'Browser-based IDE powered by WebContainers. Full Node.js in the browser.',
        category: 'code-debug',
        pricing: 'Freemium',
        tags: ['ide', 'node', 'browser', 'instant'],
        icon: '⚡',
    },
    {
        id: 'github-copilot',
        name: 'GitHub Copilot',
        url: 'https://github.com/features/copilot',
        description: 'AI pair programmer. Auto-completes code in your editor. Free for students.',
        category: 'code-debug',
        pricing: 'Freemium',
        tags: ['ai', 'autocomplete', 'student-free'],
        icon: '🤖',
    },
    {
        id: 'regex101',
        name: 'Regex101',
        url: 'https://regex101.com',
        description: 'Interactive regex tester with live explanation. Supports JS, Python, Go, and more.',
        category: 'code-debug',
        pricing: 'Free',
        tags: ['regex', 'tester', 'debug'],
        icon: '🔧',
        noSignup: true,
    },
    {
        id: 'devtoys',
        name: 'DevToys',
        url: 'https://devtoys.app',
        description: 'Swiss Army knife for developers — JSON, JWT, Base64, hash, and more in one app.',
        category: 'code-debug',
        pricing: 'Free',
        tags: ['tools', 'json', 'utilities', 'offline'],
        icon: '🧰',
    },

    // ─── DESIGN / UI ──────────────────────────────────────────────
    {
        id: 'figma',
        name: 'Figma',
        url: 'https://www.figma.com',
        description: 'Industry-standard UI/UX design tool. Collaborative, real-time, free for students.',
        category: 'design',
        pricing: 'Freemium',
        tags: ['ui', 'ux', 'collaborative', 'prototype'],
        icon: '🎨',
        hackathonPrompt: `Use Community files: Search "Hackathon UI Kit" or "Dashboard Template". Duplicate to your drafts. Replace colors with your brand. Export screens as PNG for your pitch deck.`,
    },
    {
        id: 'excalidraw',
        name: 'Excalidraw',
        url: 'https://excalidraw.com',
        description: 'Virtual whiteboard for sketching diagrams. Hand-drawn look, zero setup.',
        category: 'design',
        pricing: 'Free',
        tags: ['diagrams', 'whiteboard', 'hand-drawn'],
        icon: '📐',
        noSignup: true,
    },
    {
        id: 'remove-bg',
        name: 'Remove.bg',
        url: 'https://www.remove.bg',
        description: 'AI background removal in 5 seconds. Perfect for product shots and profile pics.',
        category: 'design',
        pricing: 'Freemium',
        tags: ['background', 'ai', 'image-edit'],
        icon: '🖼️',
        noSignup: true,
    },
    {
        id: 'coolors',
        name: 'Coolors',
        url: 'https://coolors.co',
        description: 'Color palette generator. Press spacebar to explore perfect color combinations.',
        category: 'design',
        pricing: 'Free',
        tags: ['colors', 'palette', 'design'],
        icon: '🌈',
        noSignup: true,
    },
    {
        id: 'unsplash',
        name: 'Unsplash',
        url: 'https://unsplash.com',
        description: 'High-resolution free stock photos. No attribution required.',
        category: 'design',
        pricing: 'Free',
        tags: ['photos', 'stock', 'free'],
        icon: '📷',
    },
    {
        id: 'lucide',
        name: 'Lucide Icons',
        url: 'https://lucide.dev',
        description: 'Beautiful open-source icon library. Clean, consistent, and free.',
        category: 'design',
        pricing: 'Free',
        tags: ['icons', 'open-source', 'svg'],
        icon: '💠',
        noSignup: true,
    },
    {
        id: 'shots',
        name: 'Shots.so',
        url: 'https://shots.so',
        description: 'Create beautiful mockups of your screenshots for presentations and social media.',
        category: 'design',
        pricing: 'Free',
        tags: ['mockup', 'screenshot', 'presentation'],
        icon: '📸',
        noSignup: true,
    },

    // ─── WRITING / DOCS ──────────────────────────────────────────
    {
        id: 'notion',
        name: 'Notion',
        url: 'https://www.notion.so',
        description: 'All-in-one workspace for notes, docs, projects, and wikis. Free for students.',
        category: 'writing-docs',
        pricing: 'Freemium',
        tags: ['notes', 'docs', 'wiki', 'student-free'],
        icon: '📝',
    },
    {
        id: 'grammarly',
        name: 'Grammarly',
        url: 'https://www.grammarly.com',
        description: 'AI writing assistant for grammar, clarity, and tone. Browser extension available.',
        category: 'writing-docs',
        pricing: 'Freemium',
        tags: ['grammar', 'writing', 'ai'],
        icon: '✅',
    },
    {
        id: 'overleaf',
        name: 'Overleaf',
        url: 'https://www.overleaf.com',
        description: 'Online LaTeX editor for academic papers, reports, and research documents.',
        category: 'writing-docs',
        pricing: 'Freemium',
        tags: ['latex', 'academic', 'papers', 'collaborative'],
        icon: '📄',
    },
    {
        id: 'quillbot',
        name: 'QuillBot',
        url: 'https://quillbot.com',
        description: 'AI paraphrasing and summarizing tool. Rewrite text in different tones.',
        category: 'writing-docs',
        pricing: 'Freemium',
        tags: ['paraphrase', 'summarize', 'ai'],
        icon: '🪶',
    },
    {
        id: 'hashnode',
        name: 'Hashnode',
        url: 'https://hashnode.com',
        description: 'Free developer blogging platform. Custom domain, newsletter, and AI writing assist.',
        category: 'writing-docs',
        pricing: 'Free',
        tags: ['blog', 'developer', 'free'],
        icon: '📰',
    },
    {
        id: 'gitbook',
        name: 'GitBook',
        url: 'https://www.gitbook.com',
        description: 'Modern documentation platform. Write docs in markdown with a beautiful interface.',
        category: 'writing-docs',
        pricing: 'Freemium',
        tags: ['docs', 'markdown', 'documentation'],
        icon: '📗',
    },

    // ─── MUSIC / AUDIO ────────────────────────────────────────────
    {
        id: 'aiva',
        name: 'AIVA',
        url: 'https://www.aiva.ai',
        description: 'AI music composer. Create original soundtracks in various styles including Bollywood.',
        category: 'music-audio',
        pricing: 'Freemium',
        tags: ['ai', 'music', 'composer', 'bollywood'],
        icon: '🎼',
    },
    {
        id: 'suno',
        name: 'Suno.ai',
        url: 'https://suno.com',
        description: 'AI music generation — describe a song and Suno creates vocals + instruments.',
        category: 'music-audio',
        pricing: 'Freemium',
        tags: ['ai', 'song', 'vocals', 'generation'],
        icon: '🎤',
    },
    {
        id: 'elevenlabs',
        name: 'ElevenLabs',
        url: 'https://elevenlabs.io',
        description: 'AI text-to-speech with realistic voices. Clone voices for narration and podcasts.',
        category: 'music-audio',
        pricing: 'Freemium',
        tags: ['tts', 'voice', 'ai', 'narration'],
        icon: '🔊',
    },
    {
        id: 'mubert',
        name: 'Mubert',
        url: 'https://mubert.com',
        description: 'AI-generated royalty-free background music for videos and presentations.',
        category: 'music-audio',
        pricing: 'Freemium',
        tags: ['royalty-free', 'background', 'ai'],
        icon: '🎧',
    },

    // ─── UTILITIES ────────────────────────────────────────────────
    {
        id: 'tinywow',
        name: 'TinyWow',
        url: 'https://tinywow.com',
        description: 'Free online tools suite — PDF, image, video, and file conversion tools. No signup.',
        category: 'utilities',
        pricing: 'Free',
        tags: ['pdf', 'convert', 'tools', 'free'],
        icon: '🔧',
        noSignup: true,
    },
    {
        id: 'smallpdf',
        name: 'Smallpdf',
        url: 'https://smallpdf.com',
        description: 'PDF tools — compress, convert, merge, split, and sign PDFs online.',
        category: 'utilities',
        pricing: 'Freemium',
        tags: ['pdf', 'compress', 'convert'],
        icon: '📋',
    },
    {
        id: 'calendly',
        name: 'Calendly',
        url: 'https://calendly.com',
        description: 'Schedule meetings without back-and-forth emails. Free tier available.',
        category: 'utilities',
        pricing: 'Freemium',
        tags: ['meeting', 'schedule', 'free'],
        icon: '📅',
    },
    {
        id: 'carbon',
        name: 'Carbon',
        url: 'https://carbon.now.sh',
        description: 'Create beautiful code snippet images for presentations and social media.',
        category: 'utilities',
        pricing: 'Free',
        tags: ['code', 'screenshot', 'image'],
        icon: '🖥️',
        noSignup: true,
    },
    {
        id: 'jsoncrack',
        name: 'JSON Crack',
        url: 'https://jsoncrack.com',
        description: 'Visualize JSON data as interactive graphs. Debug API responses easily.',
        category: 'utilities',
        pricing: 'Free',
        tags: ['json', 'visualize', 'debug'],
        icon: '🔗',
        noSignup: true,
    },
    {
        id: 'ray',
        name: 'Ray.so',
        url: 'https://ray.so',
        description: 'Create beautiful code screenshots with custom themes and backgrounds.',
        category: 'utilities',
        pricing: 'Free',
        tags: ['code', 'screenshot', 'beautiful'],
        icon: '🌟',
        noSignup: true,
    },
]

// ─── AI WORKFLOW TEMPLATES ──────────────────────────────────────
export const WORKFLOWS: Workflow[] = [
    {
        id: 'hackathon-demo',
        title: 'Hackathon Demo in 30 Minutes',
        description: 'Build a complete hackathon presentation with video demo from scratch.',
        icon: '🏆',
        tools: ['gamma', 'loom', 'capcut', 'vercel'],
        steps: [
            '1. Open Gamma.app → Paste your project idea → Generate a 10-slide pitch deck',
            '2. Record a live demo of your app using Loom (3 min max)',
            '3. Edit the Loom recording in CapCut — add captions, music, and transitions',
            '4. Deploy your app on Vercel → Get a live URL for the judges',
            '5. Add the Loom video link and Vercel URL to your Gamma slides',
        ],
        useCase: 'Hackathon',
    },
    {
        id: 'research-paper',
        title: 'Research Paper Sprint',
        description: 'Find papers, summarize evidence, and write a literature review in record time.',
        icon: '📚',
        tools: ['perplexity', 'consensus', 'elicit', 'overleaf', 'notebook-lm'],
        steps: [
            '1. Use Perplexity.ai to get an overview of your research topic with cited sources',
            '2. Search Consensus.app for specific claims with supporting/opposing evidence',
            '3. Use Elicit.org to systematically find and extract data from related papers',
            '4. Upload key papers to NotebookLM and ask questions across them',
            '5. Write your paper in Overleaf using the IEEE/ACM template',
        ],
        useCase: 'Research',
    },
    {
        id: 'mvp-launch',
        title: 'MVP Launch in 2 Hours',
        description: 'Go from idea to deployed app with landing page in under 2 hours.',
        icon: '🚀',
        tools: ['replit', 'v0-dev', 'supabase', 'vercel', 'canva-slides'],
        steps: [
            '1. Use v0.dev to generate your UI components from text descriptions',
            '2. Build the backend logic in Replit Agent with AI assistance',
            '3. Set up Supabase for auth + database (free tier)',
            '4. Deploy to Vercel with one click',
            '5. Create a pitch deck in Canva using startup templates',
        ],
        useCase: 'Startup / MVP',
    },
    {
        id: 'video-presentation',
        title: 'PPT + Video for Presentation',
        description: 'Create professional slides and a polished video walkthrough.',
        icon: '🎬',
        tools: ['gamma', 'loom', 'capcut', 'elevenlabs', 'remove-bg'],
        steps: [
            '1. Generate slides in Gamma.app with your topic/content',
            '2. Use Remove.bg to clean up any images for the slides',
            '3. Record a voiceover narration using ElevenLabs AI voice',
            '4. Screen-record the slide presentation with Loom',
            '5. Combine audio and video in CapCut with transitions and captions',
        ],
        useCase: 'Presentations',
    },
    {
        id: 'portfolio-deploy',
        title: 'Student Portfolio in 1 Hour',
        description: 'Build and deploy a stunning personal portfolio website.',
        icon: '💼',
        tools: ['v0-dev', 'bolt', 'github-pages', 'unsplash', 'shots'],
        steps: [
            '1. Use v0.dev or bolt.new to generate a portfolio template from a prompt',
            '2. Get professional photos from Unsplash for hero sections',
            '3. Create device mockups of your projects with Shots.so',
            '4. Push to GitHub and enable GitHub Pages for free hosting',
            '5. Add a custom domain (optional) via GitHub settings',
        ],
        useCase: 'Portfolio',
    },
    {
        id: 'content-creation',
        title: 'Social Media Content Blitz',
        description: 'Create posts, reels, and graphics for your project launch.',
        icon: '📱',
        tools: ['canva-slides', 'capcut', 'carbon', 'suno', 'invideo'],
        steps: [
            '1. Design social media graphics in Canva (Instagram, LinkedIn, Twitter)',
            '2. Create code snippet images with Carbon for tech posts',
            '3. Generate a short announcement video with InVideo AI',
            '4. Edit and add music in CapCut for reels/shorts',
            '5. (Optional) Generate a catchy jingle with Suno for branding',
        ],
        useCase: 'Marketing',
    },
    {
        id: 'academic-project',
        title: 'Academic Project Submission',
        description: 'Complete your semester project — code, docs, and presentation.',
        icon: '🎓',
        tools: ['replit', 'overleaf', 'gamma', 'excalidraw', 'github-pages'],
        steps: [
            '1. Build your project code in Replit with version control',
            '2. Draw architecture diagrams in Excalidraw',
            '3. Write your project report in Overleaf with proper formatting',
            '4. Create a defense presentation in Gamma.app',
            '5. Deploy a live demo on GitHub Pages for the viva',
        ],
        useCase: 'Academics',
    },
    {
        id: 'ai-app-prototype',
        title: 'AI App Prototype',
        description: 'Build an AI-powered app prototype for competitions or demos.',
        icon: '🤖',
        tools: ['bolt', 'supabase', 'figma', 'railway', 'loom'],
        steps: [
            '1. Design your app\'s UI in Figma using community templates',
            '2. Use bolt.new to generate a working React app from your design',
            '3. Connect to Supabase for database and auth',
            '4. Deploy the backend to Railway.app',
            '5. Record a demo with Loom for your submission',
        ],
        useCase: 'AI / ML Projects',
    },
]
