// Last Minute — Tool Directory Data
// 65+ free/low-cost tools for students, hackathons, research, and rapid prototyping

export type ToolCategory =
    | 'ppt-slides'
    | 'video-animation'
    | 'app-building'
    | 'deployment'
    | 'research-ai'
    | 'code-debug'
    | 'design'
    | 'writing-docs'
    | 'music-audio'
    | 'utilities'

export interface Tool {
    id: string
    name: string
    url: string
    description: string
    category: ToolCategory
    pricing: 'Free' | 'Freemium' | 'Free Trial' | 'Low-Cost'
    tags: string[]
    icon: string // emoji
    hackathonPrompt?: string // AI-generated prompt for hackathon use
    noSignup?: boolean
}

export interface Workflow {
    id: string
    title: string
    description: string
    icon: string
    tools: string[] // tool ids
    steps: string[]
    useCase: string
}

export const CATEGORY_META: Record<ToolCategory, { label: string; icon: string; color: string }> = {
    'ppt-slides': { label: 'PPT / Slides', icon: '📊', color: '#f59e0b' },
    'video-animation': { label: 'Video / Animation', icon: '🎬', color: '#ef4444' },
    'app-building': { label: 'App Building', icon: '🛠️', color: '#8b5cf6' },
    'deployment': { label: 'Deploy / Hosting', icon: '🚀', color: '#06b6d4' },
    'research-ai': { label: 'Research & AI', icon: '🔬', color: '#10b981' },
    'code-debug': { label: 'Code / Debug', icon: '💻', color: '#3b82f6' },
    'design': { label: 'Design / UI', icon: '🎨', color: '#ec4899' },
    'writing-docs': { label: 'Writing / Docs', icon: '✍️', color: '#f97316' },
    'music-audio': { label: 'Music / Audio', icon: '🎵', color: '#a855f7' },
    'utilities': { label: 'Utilities', icon: '🧰', color: '#64748b' },
}

export const TOOLS: Tool[] = [
    // ─── PPT / SLIDES ─────────────────────────────────────────────
    {
        id: 'gamma',
        name: 'Gamma.app',
        url: 'https://gamma.app/signup?r=irt8vkl7gwvm2wd',
        description: 'AI-powered presentation generator. Paste your topic and get a polished PPT in seconds.',
        category: 'ppt-slides',
        pricing: 'Freemium',
        tags: ['ai', 'ppt', 'slides', 'hackathon', 'presentation'],
        icon: '⚡',
        hackathonPrompt: `Create a 10-slide hackathon demo deck for [PROJECT_NAME]. Include: Problem Statement, Solution Overview, Tech Stack, Architecture Diagram placeholder, Key Features (3), Demo Screenshots placeholders, Business Model, Market Size, Team Slide, and Call to Action. Use modern dark theme with gradient accents.`,
    },
    {
        id: 'canva-slides',
        name: 'Canva Slides',
        url: 'https://www.canva.com/presentations/',
        description: 'Drag-and-drop slide maker with 1000s of free templates. Great for non-designers.',
        category: 'ppt-slides',
        pricing: 'Freemium',
        tags: ['design', 'templates', 'ppt', 'free'],
        icon: '🎨',
        hackathonPrompt: `Search "hackathon pitch deck" in templates. Pick a dark modern template. Replace placeholder text with: Slide 1 - Project name & tagline, Slide 2 - Problem, Slide 3 - Solution, Slide 4 - Demo, Slide 5 - Tech Stack, Slide 6 - Team, Slide 7 - Next Steps.`,
    },
    {
        id: 'slidesai',
        name: 'SlidesAI.io',
        url: 'https://www.slidesai.io',
        description: 'Google Slides AI add-on — paste text and auto-generate professional slides.',
        category: 'ppt-slides',
        pricing: 'Freemium',
        tags: ['google-slides', 'ai', 'addon'],
        icon: '📑',
    },
    {
        id: 'beautiful-ai',
        name: 'Beautiful.ai',
        url: 'https://www.beautiful.ai',
        description: 'Smart slide design with auto-layout. Templates adapt to your content.',
        category: 'ppt-slides',
        pricing: 'Free Trial',
        tags: ['design', 'smart-layout', 'professional'],
        icon: '✨',
    },
    {
        id: 'tome',
        name: 'Tome',
        url: 'https://tome.app',
        description: 'AI storytelling tool that creates narrative presentations from prompts.',
        category: 'ppt-slides',
        pricing: 'Freemium',
        tags: ['ai', 'narrative', 'storytelling'],
        icon: '📖',
    },
    {
        id: 'pitch',
        name: 'Pitch',
        url: 'https://pitch.com',
        description: 'Collaborative presentation software with beautiful templates and real-time editing.',
        category: 'ppt-slides',
        pricing: 'Freemium',
        tags: ['collaboration', 'templates', 'team'],
        icon: '🎯',
    },

    // ─── VIDEO / ANIMATION ────────────────────────────────────────
    {
        id: 'capcut',
        name: 'CapCut',
        url: 'https://www.capcut.com',
        description: 'Free professional video editor with effects, transitions, and AI captions.',
        category: 'video-animation',
        pricing: 'Free',
        tags: ['video', 'editing', 'free', 'effects'],
        icon: '🎬',
        hackathonPrompt: `Import your screen recording. Add: Intro title (3s) with project name, background music (lo-fi), captions via Auto Caption, smooth transitions between clips, and an outro with team name. Export at 1080p.`,
    },
    {
        id: 'runwayml',
        name: 'RunwayML',
        url: 'https://runwayml.com',
        description: 'AI video generation and editing — text-to-video, green screen, motion tracking.',
        category: 'video-animation',
        pricing: 'Freemium',
        tags: ['ai', 'video-gen', 'effects', 'ml'],
        icon: '🤖',
    },
    {
        id: 'veed',
        name: 'VEED.io',
        url: 'https://www.veed.io',
        description: 'Online video editor with subtitles, screen recording, and social media export.',
        category: 'video-animation',
        pricing: 'Freemium',
        tags: ['subtitles', 'screen-record', 'social'],
        icon: '📹',
    },
    {
        id: 'invideo',
        name: 'InVideo AI',
        url: 'https://invideo.io',
        description: 'AI video creator — describe your video and it generates one with stock footage.',
        category: 'video-animation',
        pricing: 'Freemium',
        tags: ['ai', 'auto-generate', 'stock-footage'],
        icon: '🎥',
        hackathonPrompt: `Use AI Script: "Create a 60-second product demo video for [PROJECT_NAME]. It's a [DESCRIPTION]. Show the problem, the solution, and a call to action. Use professional tech startup style."`,
    },
    {
        id: 'loom',
        name: 'Loom',
        url: 'https://www.loom.com',
        description: 'Quick screen & cam recording for demos. Share instantly with a link.',
        category: 'video-animation',
        pricing: 'Freemium',
        tags: ['screen-record', 'demo', 'quick'],
        icon: '🔴',
        hackathonPrompt: `Record a 3-minute demo: 1) Intro yourself & project (30s), 2) Show the problem you're solving (30s), 3) Live demo of your app (90s), 4) Wrap up with future plans (30s). Share the Loom link in your pitch deck.`,
    },
    {
        id: 'descript',
        name: 'Descript',
        url: 'https://www.descript.com',
        description: 'Edit video by editing text. AI-powered transcription and screen recording.',
        category: 'video-animation',
        pricing: 'Freemium',
        tags: ['transcription', 'text-edit', 'ai'],
        icon: '📝',
    },
    {
        id: 'clipchamp',
        name: 'Clipchamp',
        url: 'https://clipchamp.com',
        description: 'Microsoft free video editor with templates, stock media, and text-to-speech.',
        category: 'video-animation',
        pricing: 'Free',
        tags: ['microsoft', 'free', 'templates'],
        icon: '🎞️',
    },

    // ─── APP BUILDING ─────────────────────────────────────────────
    {
        id: 'bubble',
        name: 'Bubble.io',
        url: 'https://bubble.io',
        description: 'Full-stack no-code app builder. Build web apps with visual workflows, DB, and auth.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['no-code', 'full-stack', 'webapp'],
        icon: '🫧',
    },
    {
        id: 'adalo',
        name: 'Adalo',
        url: 'https://www.adalo.com',
        description: 'Build native mobile apps without code. Drag-and-drop with real app store publishing.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['mobile', 'no-code', 'native'],
        icon: '📱',
    },
    {
        id: 'glide',
        name: 'Glide',
        url: 'https://www.glideapps.com',
        description: 'Turn Google Sheets into beautiful apps in minutes. Perfect for MVPs.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['sheets', 'mvp', 'quick'],
        icon: '📋',
    },
    {
        id: 'replit',
        name: 'Replit Agent',
        url: 'https://replit.com',
        description: 'AI code-to-app — describe what you want and Replit builds it. Full IDE in browser.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['ai', 'code', 'ide', 'deploy'],
        icon: '⚙️',
        hackathonPrompt: `Use Replit Agent: "Build a [TYPE] web app with [FRAMEWORK]. It should have: user auth, a dashboard showing [DATA], and an API endpoint at /api/[RESOURCE]. Use a modern dark UI with Tailwind CSS. Deploy to Replit hosting."`,
    },
    {
        id: 'v0-dev',
        name: 'v0.dev',
        url: 'https://v0.dev',
        description: 'Vercel AI UI generator — describe a component and get production React code.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['ai', 'react', 'ui-gen', 'vercel'],
        icon: '▲',
    },
    {
        id: 'bolt',
        name: 'bolt.new',
        url: 'https://bolt.new',
        description: 'AI full-stack app builder by StackBlitz. Describe your app and get a running project.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['ai', 'full-stack', 'instant'],
        icon: '⚡',
    },
    {
        id: 'lovable',
        name: 'Lovable.dev',
        url: 'https://lovable.dev',
        description: 'AI app builder — create full-stack apps from natural language descriptions.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['ai', 'full-stack', 'natural-language'],
        icon: '💜',
    },
    {
        id: 'flutterflow',
        name: 'FlutterFlow',
        url: 'https://flutterflow.io',
        description: 'Visual Flutter app builder. Design, build, and deploy mobile apps with Firebase.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['flutter', 'mobile', 'visual', 'firebase'],
        icon: '🦋',
    },

    // ─── DEPLOYMENT / HOSTING ─────────────────────────────────────
    {
        id: 'vercel',
        name: 'Vercel',
        url: 'https://vercel.com',
        description: 'Instant deploy for Next.js, React, and more. Free tier with custom domains.',
        category: 'deployment',
        pricing: 'Freemium',
        tags: ['nextjs', 'react', 'deploy', 'free'],
        icon: '▲',
    },
    {
        id: 'netlify',
        name: 'Netlify Drop',
        url: 'https://app.netlify.com/drop',
        description: 'Drag-and-drop deploy. Literally drag your folder and get a live URL.',
        category: 'deployment',
        pricing: 'Free',
        tags: ['drag-drop', 'instant', 'static'],
        icon: '🌐',
        noSignup: true,
    },
    {
        id: 'render',
        name: 'Render.com',
        url: 'https://render.com',
        description: 'Deploy web services, static sites, databases, and cron jobs. Generous free tier.',
        category: 'deployment',
        pricing: 'Freemium',
        tags: ['backend', 'database', 'fullstack'],
        icon: '🟢',
    },
    {
        id: 'railway',
        name: 'Railway.app',
        url: 'https://railway.app',
        description: 'Deploy any app with one click. Supports Node, Python, Go, Docker, and more.',
        category: 'deployment',
        pricing: 'Freemium',
        tags: ['one-click', 'docker', 'backend'],
        icon: '🚂',
    },
    {
        id: 'github-pages',
        name: 'GitHub Pages',
        url: 'https://pages.github.com',
        description: 'Free static site hosting from your GitHub repo. Perfect for portfolios and docs.',
        category: 'deployment',
        pricing: 'Free',
        tags: ['github', 'static', 'free'],
        icon: '🐙',
    },
    {
        id: 'surge',
        name: 'Surge.sh',
        url: 'https://surge.sh',
        description: 'Single command deploy for static sites. No config needed.',
        category: 'deployment',
        pricing: 'Free',
        tags: ['cli', 'static', 'instant'],
        icon: '🌊',
        noSignup: true,
    },
    {
        id: 'supabase',
        name: 'Supabase',
        url: 'https://supabase.com',
        description: 'Open-source Firebase alternative with Postgres, Auth, Storage, and Edge Functions.',
        category: 'deployment',
        pricing: 'Freemium',
        tags: ['database', 'auth', 'storage', 'backend'],
        icon: '⚡',
    },

    // ─── RESEARCH & AI ────────────────────────────────────────────
    {
        id: 'perplexity',
        name: 'Perplexity.ai',
        url: 'https://www.perplexity.ai',
        description: 'AI research assistant with real-time sources. Ask anything, get cited answers.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['research', 'ai', 'citations', 'search'],
        icon: '🔍',
        hackathonPrompt: `Search: "Latest trends in [YOUR_DOMAIN] 2026 with statistics". Use the cited sources in your pitch deck. Then search: "Existing solutions for [PROBLEM] and their limitations" for competitive analysis.`,
    },
    {
        id: 'consensus',
        name: 'Consensus.app',
        url: 'https://consensus.app',
        description: 'AI-powered academic paper search. Find research evidence for any claim.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['papers', 'academic', 'evidence'],
        icon: '📚',
    },
    {
        id: 'elicit',
        name: 'Elicit.org',
        url: 'https://elicit.org',
        description: 'AI literature review tool. Finds and summarizes relevant papers for your research.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['literature-review', 'papers', 'summary'],
        icon: '🔬',
    },
    {
        id: 'scite',
        name: 'Scite.ai',
        url: 'https://scite.ai',
        description: 'See how papers cite each other — supporting, contrasting, or mentioning.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['citations', 'analysis', 'papers'],
        icon: '📖',
    },
    {
        id: 'chatgpt',
        name: 'ChatGPT',
        url: 'https://chat.openai.com',
        description: 'OpenAI conversational AI. Code, brainstorm, write, debug, and research.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['ai', 'chat', 'code', 'writing'],
        icon: '🤖',
    },
    {
        id: 'claude',
        name: 'Claude.ai',
        url: 'https://claude.ai',
        description: 'Anthropic AI assistant. Excels at long documents, coding, and analysis.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['ai', 'analysis', 'code', 'documents'],
        icon: '🧠',
    },
    {
        id: 'gemini',
        name: 'Google Gemini',
        url: 'https://gemini.google.com',
        description: 'Google AI with web search, image generation, and deep research mode.',
        category: 'research-ai',
        pricing: 'Free',
        tags: ['ai', 'google', 'search', 'multimodal'],
        icon: '💎',
    },
    {
        id: 'notebook-lm',
        name: 'NotebookLM',
        url: 'https://notebooklm.google.com',
        description: 'Google AI notebook — upload papers/docs and chat with them. Auto-generates podcasts.',
        category: 'research-ai',
        pricing: 'Free',
        tags: ['google', 'documents', 'podcast', 'study'],
        icon: '📓',
    },
    {
        id: 'semantic-scholar',
        name: 'Semantic Scholar',
        url: 'https://www.semanticscholar.org',
        description: 'AI-powered academic search engine with paper recommendations and citations.',
        category: 'research-ai',
        pricing: 'Free',
        tags: ['academic', 'papers', 'free', 'search'],
        icon: '🎓',
    },

    // ─── CODE / DEBUG ─────────────────────────────────────────────
    {
        id: 'codepen',
        name: 'CodePen',
        url: 'https://codepen.io',
        description: 'Online code playground for HTML/CSS/JS. Instant preview and sharing.',
        category: 'code-debug',
        pricing: 'Freemium',
        tags: ['playground', 'html', 'css', 'js'],
        icon: '✏️',
        noSignup: true,
    },
    {
        id: 'jsfiddle',
        name: 'JSFiddle',
        url: 'https://jsfiddle.net',
        description: 'Quick JS/HTML/CSS prototypes. Share snippets with collaborators.',
        category: 'code-debug',
        pricing: 'Free',
        tags: ['playground', 'prototype', 'share'],
        icon: '🎻',
        noSignup: true,
    },
    {
        id: 'codesandbox',
        name: 'CodeSandbox',
        url: 'https://codesandbox.io',
        description: 'Full online IDE with npm, frameworks, and instant deployment.',
        category: 'code-debug',
        pricing: 'Freemium',
        tags: ['ide', 'npm', 'react', 'vue'],
        icon: '📦',
    },
    {
        id: 'stackblitz',
        name: 'StackBlitz',
        url: 'https://stackblitz.com',
        description: 'Browser-based IDE powered by WebContainers. Full Node.js in the browser.',
        category: 'code-debug',
        pricing: 'Freemium',
        tags: ['ide', 'node', 'browser', 'instant'],
        icon: '⚡',
    },
    {
        id: 'github-copilot',
        name: 'GitHub Copilot',
        url: 'https://github.com/features/copilot',
        description: 'AI pair programmer. Auto-completes code in your editor. Free for students.',
        category: 'code-debug',
        pricing: 'Freemium',
        tags: ['ai', 'autocomplete', 'student-free'],
        icon: '🤖',
    },
    {
        id: 'regex101',
        name: 'Regex101',
        url: 'https://regex101.com',
        description: 'Interactive regex tester with live explanation. Supports JS, Python, Go, and more.',
        category: 'code-debug',
        pricing: 'Free',
        tags: ['regex', 'tester', 'debug'],
        icon: '🔧',
        noSignup: true,
    },
    {
        id: 'devtoys',
        name: 'DevToys',
        url: 'https://devtoys.app',
        description: 'Swiss Army knife for developers — JSON, JWT, Base64, hash, and more in one app.',
        category: 'code-debug',
        pricing: 'Free',
        tags: ['tools', 'json', 'utilities', 'offline'],
        icon: '🧰',
    },

    // ─── DESIGN / UI ──────────────────────────────────────────────
    {
        id: 'figma',
        name: 'Figma',
        url: 'https://www.figma.com',
        description: 'Industry-standard UI/UX design tool. Collaborative, real-time, free for students.',
        category: 'design',
        pricing: 'Freemium',
        tags: ['ui', 'ux', 'collaborative', 'prototype'],
        icon: '🎨',
        hackathonPrompt: `Use Community files: Search "Hackathon UI Kit" or "Dashboard Template". Duplicate to your drafts. Replace colors with your brand. Export screens as PNG for your pitch deck.`,
    },
    {
        id: 'excalidraw',
        name: 'Excalidraw',
        url: 'https://excalidraw.com',
        description: 'Virtual whiteboard for sketching diagrams. Hand-drawn look, zero setup.',
        category: 'design',
        pricing: 'Free',
        tags: ['diagrams', 'whiteboard', 'hand-drawn'],
        icon: '📐',
        noSignup: true,
    },
    {
        id: 'remove-bg',
        name: 'Remove.bg',
        url: 'https://www.remove.bg',
        description: 'AI background removal in 5 seconds. Perfect for product shots and profile pics.',
        category: 'design',
        pricing: 'Freemium',
        tags: ['background', 'ai', 'image-edit'],
        icon: '🖼️',
        noSignup: true,
    },
    {
        id: 'coolors',
        name: 'Coolors',
        url: 'https://coolors.co',
        description: 'Color palette generator. Press spacebar to explore perfect color combinations.',
        category: 'design',
        pricing: 'Free',
        tags: ['colors', 'palette', 'design'],
        icon: '🌈',
        noSignup: true,
    },
    {
        id: 'unsplash',
        name: 'Unsplash',
        url: 'https://unsplash.com',
        description: 'High-resolution free stock photos. No attribution required.',
        category: 'design',
        pricing: 'Free',
        tags: ['photos', 'stock', 'free'],
        icon: '📷',
    },
    {
        id: 'lucide',
        name: 'Lucide Icons',
        url: 'https://lucide.dev',
        description: 'Beautiful open-source icon library. Clean, consistent, and free.',
        category: 'design',
        pricing: 'Free',
        tags: ['icons', 'open-source', 'svg'],
        icon: '💠',
        noSignup: true,
    },
    {
        id: 'shots',
        name: 'Shots.so',
        url: 'https://shots.so',
        description: 'Create beautiful mockups of your screenshots for presentations and social media.',
        category: 'design',
        pricing: 'Free',
        tags: ['mockup', 'screenshot', 'presentation'],
        icon: '📸',
        noSignup: true,
    },

    // ─── WRITING / DOCS ──────────────────────────────────────────
    {
        id: 'notion',
        name: 'Notion',
        url: 'https://www.notion.so',
        description: 'All-in-one workspace for notes, docs, projects, and wikis. Free for students.',
        category: 'writing-docs',
        pricing: 'Freemium',
        tags: ['notes', 'docs', 'wiki', 'student-free'],
        icon: '📝',
    },
    {
        id: 'grammarly',
        name: 'Grammarly',
        url: 'https://www.grammarly.com',
        description: 'AI writing assistant for grammar, clarity, and tone. Browser extension available.',
        category: 'writing-docs',
        pricing: 'Freemium',
        tags: ['grammar', 'writing', 'ai'],
        icon: '✅',
    },
    {
        id: 'overleaf',
        name: 'Overleaf',
        url: 'https://www.overleaf.com',
        description: 'Online LaTeX editor for academic papers, reports, and research documents.',
        category: 'writing-docs',
        pricing: 'Freemium',
        tags: ['latex', 'academic', 'papers', 'collaborative'],
        icon: '📄',
    },
    {
        id: 'quillbot',
        name: 'QuillBot',
        url: 'https://quillbot.com',
        description: 'AI paraphrasing and summarizing tool. Rewrite text in different tones.',
        category: 'writing-docs',
        pricing: 'Freemium',
        tags: ['paraphrase', 'summarize', 'ai'],
        icon: '🪶',
    },
    {
        id: 'hashnode',
        name: 'Hashnode',
        url: 'https://hashnode.com',
        description: 'Free developer blogging platform. Custom domain, newsletter, and AI writing assist.',
        category: 'writing-docs',
        pricing: 'Free',
        tags: ['blog', 'developer', 'free'],
        icon: '📰',
    },
    {
        id: 'gitbook',
        name: 'GitBook',
        url: 'https://www.gitbook.com',
        description: 'Modern documentation platform. Write docs in markdown with a beautiful interface.',
        category: 'writing-docs',
        pricing: 'Freemium',
        tags: ['docs', 'markdown', 'documentation'],
        icon: '📗',
    },

    // ─── MUSIC / AUDIO ────────────────────────────────────────────
    {
        id: 'aiva',
        name: 'AIVA',
        url: 'https://www.aiva.ai',
        description: 'AI music composer. Create original soundtracks in various styles including Bollywood.',
        category: 'music-audio',
        pricing: 'Freemium',
        tags: ['ai', 'music', 'composer', 'bollywood'],
        icon: '🎼',
    },
    {
        id: 'suno',
        name: 'Suno.ai',
        url: 'https://suno.com',
        description: 'AI music generation — describe a song and Suno creates vocals + instruments.',
        category: 'music-audio',
        pricing: 'Freemium',
        tags: ['ai', 'song', 'vocals', 'generation'],
        icon: '🎤',
    },
    {
        id: 'elevenlabs',
        name: 'ElevenLabs',
        url: 'https://elevenlabs.io',
        description: 'AI text-to-speech with realistic voices. Clone voices for narration and podcasts.',
        category: 'music-audio',
        pricing: 'Freemium',
        tags: ['tts', 'voice', 'ai', 'narration'],
        icon: '🔊',
    },
    {
        id: 'mubert',
        name: 'Mubert',
        url: 'https://mubert.com',
        description: 'AI-generated royalty-free background music for videos and presentations.',
        category: 'music-audio',
        pricing: 'Freemium',
        tags: ['royalty-free', 'background', 'ai'],
        icon: '🎧',
    },

    // ─── UTILITIES ────────────────────────────────────────────────
    {
        id: 'tinywow',
        name: 'TinyWow',
        url: 'https://tinywow.com',
        description: 'Free online tools suite — PDF, image, video, and file conversion tools. No signup.',
        category: 'utilities',
        pricing: 'Free',
        tags: ['pdf', 'convert', 'tools', 'free'],
        icon: '🔧',
        noSignup: true,
    },
    {
        id: 'smallpdf',
        name: 'Smallpdf',
        url: 'https://smallpdf.com',
        description: 'PDF tools — compress, convert, merge, split, and sign PDFs online.',
        category: 'utilities',
        pricing: 'Freemium',
        tags: ['pdf', 'compress', 'convert'],
        icon: '📋',
    },
    {
        id: 'calendly',
        name: 'Calendly',
        url: 'https://calendly.com',
        description: 'Schedule meetings without back-and-forth emails. Free tier available.',
        category: 'utilities',
        pricing: 'Freemium',
        tags: ['meeting', 'schedule', 'free'],
        icon: '📅',
    },
    {
        id: 'carbon',
        name: 'Carbon',
        url: 'https://carbon.now.sh',
        description: 'Create beautiful code snippet images for presentations and social media.',
        category: 'utilities',
        pricing: 'Free',
        tags: ['code', 'screenshot', 'image'],
        icon: '🖥️',
        noSignup: true,
    },
    {
        id: 'jsoncrack',
        name: 'JSON Crack',
        url: 'https://jsoncrack.com',
        description: 'Visualize JSON data as interactive graphs. Debug API responses easily.',
        category: 'utilities',
        pricing: 'Free',
        tags: ['json', 'visualize', 'debug'],
        icon: '🔗',
        noSignup: true,
    },
    {
        id: 'ray',
        name: 'Ray.so',
        url: 'https://ray.so',
        description: 'Create beautiful code screenshots with custom themes and backgrounds.',
        category: 'utilities',
        pricing: 'Free',
        tags: ['code', 'screenshot', 'beautiful'],
        icon: '🌟',
        noSignup: true,
    },

    // ─── ADDITIONAL AI IMAGE / CREATIVE TOOLS ────────────────
    {
        id: 'midjourney',
        name: 'Midjourney',
        url: 'https://www.midjourney.com',
        description: 'AI art generation via Discord. Create stunning visuals from text prompts.',
        category: 'design',
        pricing: 'Low-Cost',
        tags: ['ai', 'art', 'image-gen', 'creative'],
        icon: '🎨',
    },
    {
        id: 'dalle',
        name: 'DALL-E 3',
        url: 'https://openai.com/dall-e-3',
        description: 'OpenAI image generator integrated into ChatGPT. Create any image from text.',
        category: 'design',
        pricing: 'Freemium',
        tags: ['ai', 'image-gen', 'openai'],
        icon: '🖼️',
    },
    {
        id: 'leonardo-ai',
        name: 'Leonardo.ai',
        url: 'https://leonardo.ai',
        description: 'AI image generation for game assets, concept art, and design. Fine-tune your own models.',
        category: 'design',
        pricing: 'Freemium',
        tags: ['ai', 'game-assets', 'art', 'custom-models'],
        icon: '🎭',
    },
    {
        id: 'canva-design',
        name: 'Canva',
        url: 'https://www.canva.com',
        description: 'All-in-one design platform with templates for logos, social media, posters, and more.',
        category: 'design',
        pricing: 'Freemium',
        tags: ['design', 'templates', 'social-media', 'logos'],
        icon: '🎨',
    },
    {
        id: 'penpot',
        name: 'Penpot',
        url: 'https://penpot.app',
        description: 'Open-source design and prototyping platform. Figma alternative with SVG-first approach.',
        category: 'design',
        pricing: 'Free',
        tags: ['open-source', 'design', 'prototype', 'svg'],
        icon: '🖌️',
    },
    {
        id: 'fontjoy',
        name: 'Fontjoy',
        url: 'https://fontjoy.com',
        description: 'AI-powered font pairing generator. Find perfect typography combinations instantly.',
        category: 'design',
        pricing: 'Free',
        tags: ['fonts', 'typography', 'ai', 'pairing'],
        icon: '🔤',
        noSignup: true,
    },
    {
        id: 'realtime-colors',
        name: 'Realtime Colors',
        url: 'https://realtimecolors.com',
        description: 'Visualize color palettes on a real website in real-time. Pick perfect scheme instantly.',
        category: 'design',
        pricing: 'Free',
        tags: ['colors', 'palette', 'live-preview'],
        icon: '🌈',
        noSignup: true,
    },

    // ─── ADDITIONAL APP / CODE TOOLS ──────────────────────────
    {
        id: 'cursor',
        name: 'Cursor AI',
        url: 'https://cursor.com',
        description: 'AI-first code editor built on VS Code. Chat with your codebase, generate code.',
        category: 'code-debug',
        pricing: 'Freemium',
        tags: ['ai', 'editor', 'code-gen', 'vs-code'],
        icon: '🖱️',
    },
    {
        id: 'windsurf',
        name: 'Windsurf',
        url: 'https://codeium.com/windsurf',
        description: 'AI-powered IDE with deep context understanding. Free AI autocomplete and chat.',
        category: 'code-debug',
        pricing: 'Free',
        tags: ['ai', 'ide', 'autocomplete', 'free'],
        icon: '🏄',
    },
    {
        id: 'github-codespaces',
        name: 'GitHub Codespaces',
        url: 'https://github.com/features/codespaces',
        description: 'Cloud development environments. Full VS Code in the browser on any repo.',
        category: 'code-debug',
        pricing: 'Freemium',
        tags: ['cloud', 'ide', 'github', 'vm'],
        icon: '☁️',
    },
    {
        id: 'typescript-playground',
        name: 'TypeScript Playground',
        url: 'https://www.typescriptlang.org/play',
        description: 'Official TypeScript playground. Test and share TypeScript code online.',
        category: 'code-debug',
        pricing: 'Free',
        tags: ['typescript', 'playground', 'test'],
        icon: '🔷',
        noSignup: true,
    },
    {
        id: 'gitpod',
        name: 'Gitpod',
        url: 'https://gitpod.io',
        description: 'Cloud dev environments that spin up in seconds. Open any GitHub repo instantly.',
        category: 'code-debug',
        pricing: 'Freemium',
        tags: ['cloud', 'dev-env', 'github', 'instant'],
        icon: '🟠',
    },
    {
        id: 'postman',
        name: 'Postman',
        url: 'https://www.postman.com',
        description: 'API development platform. Build, test, and document APIs with ease.',
        category: 'code-debug',
        pricing: 'Freemium',
        tags: ['api', 'testing', 'rest', 'graphql'],
        icon: '📮',
    },
    {
        id: 'insomnia',
        name: 'Insomnia',
        url: 'https://insomnia.rest',
        description: 'Open-source API client for REST, GraphQL, and gRPC. Beautiful and fast.',
        category: 'code-debug',
        pricing: 'Free',
        tags: ['api', 'graphql', 'open-source', 'client'],
        icon: '🌙',
    },
    {
        id: 'httpie',
        name: 'HTTPie',
        url: 'https://httpie.io',
        description: 'Modern API testing in the browser. Clean UI for sending HTTP requests.',
        category: 'code-debug',
        pricing: 'Freemium',
        tags: ['api', 'http', 'testing', 'clean-ui'],
        icon: '🔌',
    },
    {
        id: 'wakatime',
        name: 'WakaTime',
        url: 'https://wakatime.com',
        description: 'Automatic coding metrics and time tracking from your editor. Leaderboards.',
        category: 'code-debug',
        pricing: 'Freemium',
        tags: ['metrics', 'time-tracking', 'productivity'],
        icon: '⏱️',
    },

    // ─── DATABASE / BACKEND TOOLS ──────────────────────────────
    {
        id: 'firebase',
        name: 'Firebase',
        url: 'https://firebase.google.com',
        description: 'Google app platform — realtime DB, auth, hosting, cloud functions, and analytics.',
        category: 'deployment',
        pricing: 'Freemium',
        tags: ['google', 'backend', 'auth', 'realtime'],
        icon: '🔥',
    },
    {
        id: 'planetscale',
        name: 'PlanetScale',
        url: 'https://planetscale.com',
        description: 'Serverless MySQL database with branching, like Git for databases.',
        category: 'deployment',
        pricing: 'Freemium',
        tags: ['mysql', 'serverless', 'branching'],
        icon: '🌍',
    },
    {
        id: 'neon',
        name: 'Neon',
        url: 'https://neon.tech',
        description: 'Serverless Postgres with autoscaling, branching, and a generous free tier.',
        category: 'deployment',
        pricing: 'Freemium',
        tags: ['postgres', 'serverless', 'branching', 'free'],
        icon: '💚',
    },
    {
        id: 'upstash',
        name: 'Upstash',
        url: 'https://upstash.com',
        description: 'Serverless Redis and Kafka. Pay per request, perfect for edge functions.',
        category: 'deployment',
        pricing: 'Freemium',
        tags: ['redis', 'kafka', 'serverless', 'edge'],
        icon: '🟩',
    },
    {
        id: 'appwrite',
        name: 'Appwrite',
        url: 'https://appwrite.io',
        description: 'Open-source backend server with auth, DB, storage, and functions. Self-host or cloud.',
        category: 'deployment',
        pricing: 'Free',
        tags: ['open-source', 'backend', 'auth', 'self-host'],
        icon: '🏗️',
    },
    {
        id: 'convex',
        name: 'Convex',
        url: 'https://www.convex.dev',
        description: 'Reactive backend-as-a-service. Real-time queries, mutations, and serverless functions.',
        category: 'deployment',
        pricing: 'Freemium',
        tags: ['realtime', 'backend', 'serverless', 'react'],
        icon: '🔄',
    },
    {
        id: 'deno-deploy',
        name: 'Deno Deploy',
        url: 'https://deno.com/deploy',
        description: 'Globally distributed JavaScript/TypeScript runtime. Deploy serverless functions at the edge.',
        category: 'deployment',
        pricing: 'Freemium',
        tags: ['deno', 'edge', 'serverless', 'typescript'],
        icon: '🦕',
    },
    {
        id: 'fly-io',
        name: 'Fly.io',
        url: 'https://fly.io',
        description: 'Deploy Docker containers globally. Full-stack apps, databases, and distributed systems.',
        category: 'deployment',
        pricing: 'Freemium',
        tags: ['docker', 'global', 'edge', 'containers'],
        icon: '✈️',
    },
    {
        id: 'coolify',
        name: 'Coolify',
        url: 'https://coolify.io',
        description: 'Self-hostable Heroku/Netlify alternative. Deploy anything to your own server.',
        category: 'deployment',
        pricing: 'Free',
        tags: ['self-host', 'open-source', 'deploy', 'docker'],
        icon: '❄️',
    },

    // ─── ADDITIONAL RESEARCH & AI TOOLS ────────────────────────
    {
        id: 'deepseek',
        name: 'DeepSeek',
        url: 'https://chat.deepseek.com',
        description: 'Advanced AI reasoning model. Excels at coding, math, and complex analysis tasks.',
        category: 'research-ai',
        pricing: 'Free',
        tags: ['ai', 'coding', 'reasoning', 'math'],
        icon: '🐋',
    },
    {
        id: 'phind',
        name: 'Phind',
        url: 'https://www.phind.com',
        description: 'AI search engine for developers. Get code answers with sources in seconds.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['ai', 'code-search', 'developer', 'fast'],
        icon: '🔎',
    },
    {
        id: 'you-com',
        name: 'You.com',
        url: 'https://you.com',
        description: 'AI search engine with multiple modes — code, research, writing, and image generation.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['search', 'ai', 'multi-mode'],
        icon: '🔮',
    },
    {
        id: 'huggingface',
        name: 'Hugging Face',
        url: 'https://huggingface.co',
        description: 'The GitHub of ML. Explore, run, and deploy thousands of AI models for free.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['ml', 'models', 'open-source', 'deploy'],
        icon: '🤗',
    },
    {
        id: 'kaggle',
        name: 'Kaggle',
        url: 'https://www.kaggle.com',
        description: 'Data science platform with datasets, competitions, and free GPU notebooks.',
        category: 'research-ai',
        pricing: 'Free',
        tags: ['data-science', 'datasets', 'gpu', 'competitions'],
        icon: '📊',
    },
    {
        id: 'colab',
        name: 'Google Colab',
        url: 'https://colab.research.google.com',
        description: 'Free Jupyter notebooks with GPU/TPU access. Run ML experiments in the cloud.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['jupyter', 'gpu', 'ml', 'python', 'free'],
        icon: '📒',
    },
    {
        id: 'grok',
        name: 'Grok',
        url: 'https://grok.x.ai',
        description: 'xAI conversational model with real-time X integration and a fun personality.',
        category: 'research-ai',
        pricing: 'Freemium',
        tags: ['ai', 'chat', 'realtime', 'x'],
        icon: '🎮',
    },
    {
        id: 'copilot-ms',
        name: 'Microsoft Copilot',
        url: 'https://copilot.microsoft.com',
        description: 'Microsoft AI assistant with web search, image generation, and Office integration.',
        category: 'research-ai',
        pricing: 'Free',
        tags: ['ai', 'microsoft', 'search', 'office'],
        icon: '🪟',
    },

    // ─── ADDITIONAL VIDEO / ANIMATION ──────────────────────────
    {
        id: 'synthesia',
        name: 'Synthesia',
        url: 'https://www.synthesia.io',
        description: 'AI video generator with realistic avatars. Create presenter videos without cameras.',
        category: 'video-animation',
        pricing: 'Free Trial',
        tags: ['ai', 'avatar', 'presenter', 'no-camera'],
        icon: '🧑‍💼',
    },
    {
        id: 'heygen',
        name: 'HeyGen',
        url: 'https://www.heygen.com',
        description: 'AI video platform with talking avatars, voice cloning, and multilingual dubbing.',
        category: 'video-animation',
        pricing: 'Freemium',
        tags: ['ai', 'avatar', 'voice-clone', 'dubbing'],
        icon: '🗣️',
    },
    {
        id: 'pika',
        name: 'Pika',
        url: 'https://pika.art',
        description: 'AI video generation and editing. Create and modify videos from text or images.',
        category: 'video-animation',
        pricing: 'Freemium',
        tags: ['ai', 'video-gen', 'text-to-video'],
        icon: '⚡',
    },
    {
        id: 'obs',
        name: 'OBS Studio',
        url: 'https://obsproject.com',
        description: 'Free open-source screen recording and live streaming software. Professional grade.',
        category: 'video-animation',
        pricing: 'Free',
        tags: ['recording', 'streaming', 'open-source'],
        icon: '📡',
    },

    // ─── ADDITIONAL WRITING / DOCS / NOTES ────────────────────
    {
        id: 'obsidian',
        name: 'Obsidian',
        url: 'https://obsidian.md',
        description: 'Knowledge base on local Markdown files. Link notes, create graphs, use plugins.',
        category: 'writing-docs',
        pricing: 'Free',
        tags: ['notes', 'markdown', 'graph', 'local-first'],
        icon: '💎',
    },
    {
        id: 'typst',
        name: 'Typst',
        url: 'https://typst.app',
        description: 'Modern LaTeX replacement. Faster compilation, clean syntax, live preview.',
        category: 'writing-docs',
        pricing: 'Freemium',
        tags: ['latex', 'typesetting', 'academic', 'modern'],
        icon: '📃',
    },
    {
        id: 'readme-so',
        name: 'readme.so',
        url: 'https://readme.so',
        description: 'Simple drag-and-drop editor to create beautiful README files for GitHub.',
        category: 'writing-docs',
        pricing: 'Free',
        tags: ['readme', 'github', 'markdown'],
        icon: '📖',
        noSignup: true,
    },
    {
        id: 'coda',
        name: 'Coda',
        url: 'https://coda.io',
        description: 'All-in-one doc that combines docs, spreadsheets, and apps. Automate workflows.',
        category: 'writing-docs',
        pricing: 'Freemium',
        tags: ['docs', 'spreadsheet', 'automation'],
        icon: '📋',
    },
    {
        id: 'hemingway',
        name: 'Hemingway Editor',
        url: 'https://hemingwayapp.com',
        description: 'Makes your writing bold and clear. Highlights complex sentences and passive voice.',
        category: 'writing-docs',
        pricing: 'Free',
        tags: ['writing', 'clarity', 'editing'],
        icon: '✍️',
        noSignup: true,
    },

    // ─── ADDITIONAL MUSIC / AUDIO ──────────────────────────────
    {
        id: 'udio',
        name: 'Udio',
        url: 'https://www.udio.com',
        description: 'AI music generation with vocals. Create full songs from text descriptions.',
        category: 'music-audio',
        pricing: 'Freemium',
        tags: ['ai', 'music', 'vocals', 'songs'],
        icon: '🎶',
    },
    {
        id: 'audacity',
        name: 'Audacity',
        url: 'https://www.audacityteam.org',
        description: 'Free open-source audio editor. Record, edit, and mix audio. Professional quality.',
        category: 'music-audio',
        pricing: 'Free',
        tags: ['audio', 'editor', 'open-source', 'free'],
        icon: '🎚️',
    },
    {
        id: 'soundraw',
        name: 'Soundraw',
        url: 'https://soundraw.io',
        description: 'AI music generator for creators. Customize mood, genre, and length for unique tracks.',
        category: 'music-audio',
        pricing: 'Freemium',
        tags: ['ai', 'music', 'royalty-free', 'custom'],
        icon: '🎹',
    },
    {
        id: 'audio-noodl',
        name: 'Beatoven.ai',
        url: 'https://www.beatoven.ai',
        description: 'AI music composition for video. Generate mood-based background music.',
        category: 'music-audio',
        pricing: 'Freemium',
        tags: ['ai', 'video-music', 'mood', 'composition'],
        icon: '🎵',
    },

    // ─── ADDITIONAL UTILITIES ──────────────────────────────────
    {
        id: 'squoosh',
        name: 'Squoosh',
        url: 'https://squoosh.app',
        description: 'Google image compressor. Reduce image sizes with visual quality comparison.',
        category: 'utilities',
        pricing: 'Free',
        tags: ['image', 'compress', 'google', 'web-perf'],
        icon: '🗜️',
        noSignup: true,
    },
    {
        id: 'transform-tools',
        name: 'transform.tools',
        url: 'https://transform.tools',
        description: 'Convert between code formats — JSON to TS, HTML to JSX, CSS to Tailwind, and more.',
        category: 'utilities',
        pricing: 'Free',
        tags: ['convert', 'json', 'typescript', 'jsx'],
        icon: '🔄',
        noSignup: true,
    },
    {
        id: 'wappalyzer',
        name: 'Wappalyzer',
        url: 'https://www.wappalyzer.com',
        description: 'Identify technologies used on any website. Browser extension for tech stack detection.',
        category: 'utilities',
        pricing: 'Freemium',
        tags: ['tech-stack', 'detection', 'browser-ext'],
        icon: '🔍',
    },
    {
        id: 'bundlephobia',
        name: 'Bundlephobia',
        url: 'https://bundlephobia.com',
        description: 'Find the cost of adding an npm package. See bundle size before installing.',
        category: 'utilities',
        pricing: 'Free',
        tags: ['npm', 'bundle-size', 'performance'],
        icon: '📦',
        noSignup: true,
    },
    {
        id: 'caniuse',
        name: 'Can I Use',
        url: 'https://caniuse.com',
        description: 'Browser compatibility tables for HTML5, CSS3, and JavaScript features.',
        category: 'utilities',
        pricing: 'Free',
        tags: ['browser', 'compatibility', 'css', 'html'],
        icon: '🌐',
        noSignup: true,
    },
    {
        id: 'quicktype',
        name: 'quicktype.io',
        url: 'https://quicktype.io',
        description: 'Generate types from JSON. Supports TypeScript, Python, Go, Swift, and more.',
        category: 'utilities',
        pricing: 'Free',
        tags: ['types', 'json', 'typescript', 'code-gen'],
        icon: '⚡',
        noSignup: true,
    },
    {
        id: 'dbdiagram',
        name: 'dbdiagram.io',
        url: 'https://dbdiagram.io',
        description: 'Draw database diagrams by writing code. Export to SQL, share with team.',
        category: 'utilities',
        pricing: 'Freemium',
        tags: ['database', 'diagram', 'sql', 'erd'],
        icon: '🗄️',
    },
    {
        id: 'mermaid-live',
        name: 'Mermaid Live',
        url: 'https://mermaid.live',
        description: 'Create flowcharts, sequence diagrams, and more with Mermaid syntax.',
        category: 'utilities',
        pricing: 'Free',
        tags: ['diagrams', 'flowchart', 'markdown'],
        icon: '🧜‍♀️',
        noSignup: true,
    },
    {
        id: 'svgl',
        name: 'SVGL',
        url: 'https://svgl.app',
        description: 'Beautiful collection of SVG logos for tech brands. Copy as SVG or React component.',
        category: 'utilities',
        pricing: 'Free',
        tags: ['svg', 'logos', 'icons', 'brands'],
        icon: '🏷️',
        noSignup: true,
    },
    {
        id: 'shapedivider',
        name: 'Shape Divider',
        url: 'https://www.shapedivider.app',
        description: 'Generate custom SVG section dividers for websites. Copy CSS code instantly.',
        category: 'utilities',
        pricing: 'Free',
        tags: ['svg', 'css', 'design', 'shapes'],
        icon: '📐',
        noSignup: true,
    },

    // ─── APP BUILDING ADDITIONS ──────────────────────────────────
    {
        id: 'retool',
        name: 'Retool',
        url: 'https://retool.com',
        description: 'Build internal tools fast. Drag-and-drop with DB connections and API integrations.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['internal-tools', 'admin', 'database', 'low-code'],
        icon: '🔧',
    },
    {
        id: 'streamlit',
        name: 'Streamlit',
        url: 'https://streamlit.io',
        description: 'Turn Python scripts into beautiful web apps. Perfect for data science and ML projects.',
        category: 'app-building',
        pricing: 'Free',
        tags: ['python', 'data-science', 'ml', 'dashboards'],
        icon: '🐍',
    },
    {
        id: 'gradio',
        name: 'Gradio',
        url: 'https://gradio.app',
        description: 'Build ML demo interfaces in Python. Share via link or embed in HuggingFace.',
        category: 'app-building',
        pricing: 'Free',
        tags: ['ml', 'demo', 'python', 'huggingface'],
        icon: '🤖',
    },
    {
        id: 'supabase-studio',
        name: 'Supabase Studio',
        url: 'https://supabase.com/dashboard',
        description: 'Visual database manager with table editor, SQL editor, and real-time data viewer.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['database', 'postgres', 'admin', 'visual'],
        icon: '⚡',
    },
    {
        id: 'directus',
        name: 'Directus',
        url: 'https://directus.io',
        description: 'Open-source headless CMS and data platform. Instant API from any SQL database.',
        category: 'app-building',
        pricing: 'Freemium',
        tags: ['cms', 'api', 'open-source', 'headless'],
        icon: '🐰',
    },
    {
        id: 'appsmith',
        name: 'Appsmith',
        url: 'https://www.appsmith.com',
        description: 'Open-source low-code platform to build admin panels, internal tools, and dashboards.',
        category: 'app-building',
        pricing: 'Free',
        tags: ['low-code', 'admin', 'open-source', 'dashboards'],
        icon: '🛠️',
    },

    // ─── PPT / SLIDES ADDITIONS ──────────────────────────────────
    {
        id: 'prezi',
        name: 'Prezi',
        url: 'https://prezi.com',
        description: 'Zoomable presentation software with non-linear storytelling and dynamic paths.',
        category: 'ppt-slides',
        pricing: 'Freemium',
        tags: ['presentation', 'zoom', 'non-linear', 'dynamic'],
        icon: '🔭',
    },
    {
        id: 'visme',
        name: 'Visme',
        url: 'https://www.visme.co',
        description: 'Visual content creation for presentations, infographics, and data visualizations.',
        category: 'ppt-slides',
        pricing: 'Freemium',
        tags: ['infographic', 'data-viz', 'templates'],
        icon: '📊',
    },
    {
        id: 'mentimeter',
        name: 'Mentimeter',
        url: 'https://www.mentimeter.com',
        description: 'Interactive presentation tool with live polls, quizzes, and audience engagement.',
        category: 'ppt-slides',
        pricing: 'Freemium',
        tags: ['interactive', 'polls', 'quiz', 'audience'],
        icon: '📣',
    },
    {
        id: 'google-slides',
        name: 'Google Slides',
        url: 'https://slides.google.com',
        description: 'Free presentation maker with real-time collaboration and Google Drive integration.',
        category: 'ppt-slides',
        pricing: 'Free',
        tags: ['google', 'free', 'collaboration', 'drive'],
        icon: '📑',
    },
]


// ─── AI WORKFLOW TEMPLATES ──────────────────────────────────────
export const WORKFLOWS: Workflow[] = [
    {
        id: 'hackathon-demo',
        title: 'Hackathon Demo in 30 Minutes',
        description: 'Build a complete hackathon presentation with video demo from scratch.',
        icon: '🏆',
        tools: ['gamma', 'loom', 'capcut', 'vercel'],
        steps: [
            '1. Open Gamma.app → Paste your project idea → Generate a 10-slide pitch deck',
            '2. Record a live demo of your app using Loom (3 min max)',
            '3. Edit the Loom recording in CapCut — add captions, music, and transitions',
            '4. Deploy your app on Vercel → Get a live URL for the judges',
            '5. Add the Loom video link and Vercel URL to your Gamma slides',
        ],
        useCase: 'Hackathon',
    },
    {
        id: 'research-paper',
        title: 'Research Paper Sprint',
        description: 'Find papers, summarize evidence, and write a literature review in record time.',
        icon: '📚',
        tools: ['perplexity', 'consensus', 'elicit', 'overleaf', 'notebook-lm'],
        steps: [
            '1. Use Perplexity.ai to get an overview of your research topic with cited sources',
            '2. Search Consensus.app for specific claims with supporting/opposing evidence',
            '3. Use Elicit.org to systematically find and extract data from related papers',
            '4. Upload key papers to NotebookLM and ask questions across them',
            '5. Write your paper in Overleaf using the IEEE/ACM template',
        ],
        useCase: 'Research',
    },
    {
        id: 'mvp-launch',
        title: 'MVP Launch in 2 Hours',
        description: 'Go from idea to deployed app with landing page in under 2 hours.',
        icon: '🚀',
        tools: ['replit', 'v0-dev', 'supabase', 'vercel', 'canva-slides'],
        steps: [
            '1. Use v0.dev to generate your UI components from text descriptions',
            '2. Build the backend logic in Replit Agent with AI assistance',
            '3. Set up Supabase for auth + database (free tier)',
            '4. Deploy to Vercel with one click',
            '5. Create a pitch deck in Canva using startup templates',
        ],
        useCase: 'Startup / MVP',
    },
    {
        id: 'video-presentation',
        title: 'PPT + Video for Presentation',
        description: 'Create professional slides and a polished video walkthrough.',
        icon: '🎬',
        tools: ['gamma', 'loom', 'capcut', 'elevenlabs', 'remove-bg'],
        steps: [
            '1. Generate slides in Gamma.app with your topic/content',
            '2. Use Remove.bg to clean up any images for the slides',
            '3. Record a voiceover narration using ElevenLabs AI voice',
            '4. Screen-record the slide presentation with Loom',
            '5. Combine audio and video in CapCut with transitions and captions',
        ],
        useCase: 'Presentations',
    },
    {
        id: 'portfolio-deploy',
        title: 'Student Portfolio in 1 Hour',
        description: 'Build and deploy a stunning personal portfolio website.',
        icon: '💼',
        tools: ['v0-dev', 'bolt', 'github-pages', 'unsplash', 'shots'],
        steps: [
            '1. Use v0.dev or bolt.new to generate a portfolio template from a prompt',
            '2. Get professional photos from Unsplash for hero sections',
            '3. Create device mockups of your projects with Shots.so',
            '4. Push to GitHub and enable GitHub Pages for free hosting',
            '5. Add a custom domain (optional) via GitHub settings',
        ],
        useCase: 'Portfolio',
    },
    {
        id: 'content-creation',
        title: 'Social Media Content Blitz',
        description: 'Create posts, reels, and graphics for your project launch.',
        icon: '📱',
        tools: ['canva-slides', 'capcut', 'carbon', 'suno', 'invideo'],
        steps: [
            '1. Design social media graphics in Canva (Instagram, LinkedIn, Twitter)',
            '2. Create code snippet images with Carbon for tech posts',
            '3. Generate a short announcement video with InVideo AI',
            '4. Edit and add music in CapCut for reels/shorts',
            '5. (Optional) Generate a catchy jingle with Suno for branding',
        ],
        useCase: 'Marketing',
    },
    {
        id: 'academic-project',
        title: 'Academic Project Submission',
        description: 'Complete your semester project — code, docs, and presentation.',
        icon: '🎓',
        tools: ['replit', 'overleaf', 'gamma', 'excalidraw', 'github-pages'],
        steps: [
            '1. Build your project code in Replit with version control',
            '2. Draw architecture diagrams in Excalidraw',
            '3. Write your project report in Overleaf with proper formatting',
            '4. Create a defense presentation in Gamma.app',
            '5. Deploy a live demo on GitHub Pages for the viva',
        ],
        useCase: 'Academics',
    },
    {
        id: 'ai-app-prototype',
        title: 'AI App Prototype',
        description: 'Build an AI-powered app prototype for competitions or demos.',
        icon: '🤖',
        tools: ['bolt', 'supabase', 'figma', 'railway', 'loom'],
        steps: [
            '1. Design your app\'s UI in Figma using community templates',
            '2. Use bolt.new to generate a working React app from your design',
            '3. Connect to Supabase for database and auth',
            '4. Deploy the backend to Railway.app',
            '5. Record a demo with Loom for your submission',
        ],
        useCase: 'AI / ML Projects',
    },
]
