import { Metadata } from 'next';
import Navbar from '@/components/landing/Navbar';
import Footer from '@/components/landing/Footer';
import { ErrorBoundary } from '@/components/landing/ErrorBoundary';

export const metadata: Metadata = {
  title: 'Terms & Conditions | Ganapathi Mentor AI',
  description: 'Enterprise Terms of Service for Ganapathi Mentor AI.',
};

export default function TermsPage() {
  return (
    <main
      className="min-h-screen overflow-x-hidden flex flex-col bg-[#050505] text-white"
    >
      <Navbar />

      <section className="flex-grow pt-32 pb-24 px-6 md:px-10 lg:px-16 max-w-4xl mx-auto w-full">
        <h1 className="text-[clamp(2.5rem,6vw,4rem)] font-black uppercase tracking-[-0.04em] mb-12">
          Terms & <span className="text-[#FF4500]">Conditions</span>
        </h1>

        <div className="font-mono text-[13px] text-[#9CA3AF] leading-relaxed space-y-8">
          <p>
            Last updated: July 2026.
          </p>

          <h2 className="text-[16px] font-bold text-[#FFFFFF] uppercase tracking-[0.1em] mt-12 mb-4">
            1. Master Services Agreement
          </h2>
          <p>
            By accessing or deploying the Ganapathi Mentor AI platform, you agree to these Enterprise Terms of Service. These terms constitute a legally binding agreement between your organization and Neural Code Symbiosis.
          </p>

          <h2 className="text-[16px] font-bold text-[#FFFFFF] uppercase tracking-[0.1em] mt-12 mb-4">
            2. SLA & Uptime Guarantees
          </h2>
          <p>
            Enterprise tier customers are guaranteed a 99.9% uptime SLA. In the event of downtime exceeding the SLA limit, service credits will be issued in accordance with the enterprise contract addendum.
          </p>

          <h2 className="text-[16px] font-bold text-[#FFFFFF] uppercase tracking-[0.1em] mt-12 mb-4">
            3. Intellectual Property
          </h2>
          <p>
            Your code remains your code. Neural Code Symbiosis asserts no ownership rights over the code, architectures, or designs generated by the AI models while using our platform. You retain full copyright to your proprietary outputs.
          </p>

          <h2 className="text-[16px] font-bold text-[#FFFFFF] uppercase tracking-[0.1em] mt-12 mb-4">
            4. Acceptable Use
          </h2>
          <p>
            The platform may not be used to automatically generate malicious code, engage in automated denial-of-service testing without authorization, or otherwise violate the AWS Acceptable Use Policy.
          </p>
        </div>
      </section>

      <ErrorBoundary>
        <Footer />
      </ErrorBoundary>
    </main>
  );
}
